### ISSUE TITLE
Extension repos should automatically open PRs pull in changes from the template repository

### ISSUE THREAD

**Issue by cdrx** [nicoconsultancy/imm-extension-template#19]

**Comment by Pete-Hamlin** [comment]
So it seems triggering an action off an event in another repo is a collosal PITA to sccomplish. We would essentially have to listen for the webhook that is fired by the repo we want to watch (the template) and trigger a build off that.

Alternatively, the much easier/lazier way would be to trigger a weekly cron action that runs `cruft update` and creates a PR with the diff.

@cdrx do you have any particular preference on which method we use?

**Comment by cdrx** [comment]
> Alternatively, the much easier/lazier way would be to trigger a weekly cron action that runs cruft update and creates a PR with the diff.

I think this is fine tbh. Please add a workflow dispatch trigger so we can run it manually if needed.
